version: "3"

services:
  app:
    ports:
      - 42002:22/tcp
      - 42000:80/tcp
      - 42003:443/tcp
      - 42004:35729/tcp
      - 42005:8080/tcp
    environment:
      COMPOSE_PROJECT_NAME: container_name
      DWL_LOCAL_LANG: 'en_US:en'
      DWL_LOCAL: 'en_US.UTF-8'
      DWL_USER_NAME: 'username'
      DWL_USER_PASSWD: 'secret'
      DWL_USER_ID: '1000'
      DWL_SSH_ACCESS: 'false'
    tty: true
    stdin_open: true
    hostname: localhost
    image: davask/d-node:6-d8.8
    networks:
      - dwlhost
    volumes:
      - ./volumes/home/host:/dwl/home/host

networks:
    dwlhost:
        external: true

# docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dwlhost
# export COMPOSE_HTTP_TIMEOUT=600;
# docker exec -ti proxy_reverse_1 sh -c 'bash /dwl/init.sh'
# docker-compose -f /home/dwl/docker-images/http/d-node/docker-compose.yml up -d
